name: Generate and Push Articles

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Tambahkan blok permissions di sini agar bisa Read & Write
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Generator Script
        run: python generator.py
